name: External Workflow

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      EXAMPLE_ENV: ${{ inputs.param1 }}
      ADDITIONAL_ENV1: example_value1
      ADDITIONAL_ENV2: example_value2
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run some example logic
        run: |
          echo "Running some example logic with $EXAMPLE_ENV"
          echo "Using additional environment variables: $ADDITIONAL_ENV1, $ADDITIONAL_ENV2"
          echo "Environment: $ENVIRONMENT"
          echo "example_output=${{ env.EXAMPLE_ENV }}" >> $GITHUB_ENV
          echo "additional_output1=${{ env.ADDITIONAL_ENV1 }}" >> $GITHUB_ENV
          echo "additional_output2=${{ env.ADDITIONAL_ENV2 }}" >> $GITHUB_ENV
          echo "environment_output=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV
