name: Final Workflow

on: 
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  use-external-output:
    runs-on: ubuntu-latest

    needs: call-external-workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use output from external workflow
        env:
          EXTERNAL_OUTPUT: ${{ needs.call-external-workflow.outputs.example_output }}
          ADDITIONAL_OUTPUT1: ${{ needs.call-external-workflow.outputs.additional_output1 }}
          ADDITIONAL_OUTPUT2: ${{ needs.call-external-workflow.outputs.additional_output2 }}
        run: |
          echo "Using external output: $EXTERNAL_OUTPUT"
          echo "Using additional outputs: $ADDITIONAL_OUTPUT1, $ADDITIONAL_OUTPUT2"
