name: External Workflow

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      EXAMPLE_ENV: ${{ inputs.param1 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run some example logic
        run: |
          echo "Running some example logic with $EXAMPLE_ENV"
          echo "result=example_result" >> $GITHUB_ENV

      - name: Set output
        id: set-output
        run: echo "example_output=${{ env.EXAMPLE_ENV }}" >> $GITHUB_ENV
        
