name: Final Workflow

on: 
 workflow_call:

jobs:
  use-external-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use output from external workflow
        env:
          EXTERNAL_OUTPUT: ${{ github.event.workflow_run.jobs.call-external-workflow.outputs.example_output }}
          ADDITIONAL_OUTPUT1: ${{ github.event.workflow_run.jobs.call-external-workflow.outputs.additional_output1 }}
          ADDITIONAL_OUTPUT2: ${{ github.event.workflow_run.jobs.call-external-workflow.outputs.additional_output2 }}
          ENVIRONMENT_OUTPUT: ${{ github.event.workflow_run.jobs.call-external-workflow.outputs.environment_output }}
        run: |
          echo "Using external output: $EXTERNAL_OUTPUT"
          echo "Using additional outputs: $ADDITIONAL_OUTPUT1, $ADDITIONAL_OUTPUT2"
          echo "Environment: $ENVIRONMENT_OUTPUT"
