name: First Workflow

on: 
  workflow_dispatch:

jobs:
  call-external-workflow:
    uses: ./.github/workflows/external-workflow.yml
    with:
      param1: 'mutiyala'
      ENVIRONMENT: non-prod

  call-final:
    needs: call-external-workflow
    uses: ./.github/workflows/final-workflow.yml
