name: Final Workflow

on: 
  workflow_call:
    inputs:
      example_output:
        required: true
        type: string
      additional_output1:
        required: true
        type: string
      additional_output2:
        required: true
        type: string
      environment_output:
        required: true
        type: string

jobs:
  use-external-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use output from external workflow
        env:
          EXTERNAL_OUTPUT: ${{ inputs.example_output }}
          ADDITIONAL_OUTPUT1: ${{ inputs.additional_output1 }}
          ADDITIONAL_OUTPUT2: ${{ inputs.additional_output2 }}
          ENVIRONMENT_OUTPUT: ${{ inputs.environment_output }}
        run: |
          echo "Using external output: $EXTERNAL_OUTPUT"
          echo "Using additional outputs: $ADDITIONAL_OUTPUT1, $ADDITIONAL_OUTPUT2"
          echo "Environment: $ENVIRONMENT_OUTPUT"
