name: First Workflow

on: 
  workflow_dispatch:

jobs:
  call-external-workflow:
    uses: ./.github/workflows/external-workflow.yml
    with:
      param1: 'value1'
    secrets: inherit

env:
  ENVIRONMENT: non-prod
